---

- hosts: default
  gather_facts: false

  vars:
    install_device: "/dev/vda"
    python_version: "3.8"

  tasks:
    - name: "install python3~={{ python_version }}"
      raw: "apk add python3~={{ python_version }}"

    - name: gather ansible facts
      setup:

    - name: push answerfile
      template:
        src: "answerfile.j2"
        dest: "/root/answerfile"

    - name: set root password
      user:
        name: "root"
        password: "*"

    - name: setup alpine
      shell: "printf \"y\\\n\" | setup-alpine -e -f /root/answerfile"

    - name: mount installed system
      mount:
        state: mounted
        fstype: "{{item.t}}"
        opts: "{{item.o | default(omit)}}"
        src: "{{item.dev}}"
        path: "{{item.mntpt}}"
      loop:
        - {t: "ext4", dev: "{{install_device}}2", mntpt: "/mnt"}
        - {t: "ext4", dev: "{{install_device}}1", mntpt: "/mnt/boot"}
        - {t: "proc", dev: "/proc", mntpt: "/mnt/proc"}
        - {t: "devtmpfs", o: "rbind", dev: "/dev", mntpt: "/mnt/dev"}
        - {t: "sysfs", o: "rbind", dev: "/sys", mntpt: "/mnt/sys"}

    - name: add sftp link for ansible sftp
      file:
        path: /mnt/usr/lib/sftp-server
        src: ssh/sftp-server
        state: link

    - name: disable ssh password auth
      lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "^#?PasswordAuthentication (no|yes)$"
        line: "PasswordAuthentication no"
        validate: "sshd -T -f %s"

    - name: copy ssh pubkeys
      authorized_key:
        user: "root"
        path: "/mnt/root/.ssh/authorized_keys"
        exclusive: true
        key: "\
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO2qXLAsQr5WbMwgYQW\
          KOYrFWkl+lB/c6knvyJoGdUCH\
        "
        comment: "infra-root master key"
