---

- hosts: default
  gather_facts: no

  vars:
    install_device: "/dev/vda"

  tasks:
    - name: install python3
      raw: "apk add python3"

    - name: gather ansible facts
      setup:

    - name: push answerfile
      template:
        src: "answerfile.j2"
        dest: "/root/answerfile"

    - name: set root password
      user:
        name: "root"
        password: "*"

    - name: setup alpine
      shell: "printf \"y\\\n\" | setup-alpine -e -f /root/answerfile"

    - name: mount installed system
      mount:
        path: "/mnt"
        src: "{{install_device}}2"
        fstype: ext4
        state: mounted

    - name: add sftp link for ansible sftp
      file:
        path: /usr/lib/sftp-server
        src: ssh/sftp-server
        state: link

    - name: disable ssh password auth
      replace:
        path: "/etc/ssh/sshd_config"
        regexp: "^#?PasswordAuthentication (no|yes)$"
        replace: "PasswordAuthentication no"

    - name: copy ssh pubkeys
      authorized_key:
        user: "root"
        path: "/mnt/root/.ssh/authorized_keys"
        exclusive: yes
        key: |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO2qXLAsQr5WbMwgYQWKOYrFWkl+lB/c6knvyJoGdUCH
